name: main

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branches:
      - 'main'

jobs:
  check:
    name: Check rm1masm quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking
        run: |
          make check
